sudo: required
services:
    - docker
before_install:
    - docker build -t magazargaryan/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true magazargaryan/react-test npm test

after_success:
    - docker build -t magazargaryan/multi-client ./client
    - docker build -t magazargaryan/multi-nginx ./nginx
    - docker build -t magazargaryan/multi-server ./server
    - docker build -t magazargaryan/multi-worker ./worker

    - echo "$DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin"

    - docker push magazargaryawn/multi-client
    - docker push magazargaryawn/multi-nginx
    - docker push magazargaryawn/multi-server
    - docker push magazargaryawn/multi-worker